# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])
print(arr)

[0 0 0 0 0 0 0 0 0]


#### Create an array of 10 ones

In [3]:
arr=np.array([1,1,1,1,1,1,1,1,1,1])
print(arr)

[1 1 1 1 1 1 1 1 1 1]


#### Create an array of 10 fives

In [4]:
arr=np.array([5,5,5,5,5,5,5,5,5,5])
print(arr)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [5]:
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [6]:
arr=np.arange(10,51)
print(arr[::2])

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [8]:
arr=np.array([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]])
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [9]:
from numpy import random
x = random.rand()
print(x)

0.8412783859158103


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
from numpy import random
x=random.normal(size=(1,25))
print(x)

[[-2.14723234e-01 -5.38093543e-01 -2.07786979e-01  1.19110990e-01
   5.58747352e-02  2.21650659e+00 -1.08086440e+00 -1.77360599e+00
  -6.85410086e-02 -1.21010169e+00 -1.63534315e+00 -5.81319219e-01
   4.23588201e-01  1.17202142e+00 -1.39454340e-01  2.08390192e-03
   1.34692060e+00  9.32574591e-01  1.06631408e+00 -8.38384342e-01
   9.71455017e-02  1.96879510e+00  1.54695460e+00  5.92919708e-01
   4.50184055e-01]]


#### Create the following matrix:

In [11]:
arr=np.linspace(0.01,1.,num=100).reshape(10,10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
arr=np.linspace(0.01,1.,num=20)
print(arr)

[0.01       0.06210526 0.11421053 0.16631579 0.21842105 0.27052632
 0.32263158 0.37473684 0.42684211 0.47894737 0.53105263 0.58315789
 0.63526316 0.68736842 0.73947368 0.79157895 0.84368421 0.89578947
 0.94789474 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
arr=np.linspace(1,25,num=25).reshape(5,5)
print(arr)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [14]:
arr=np.linspace(1,25,num=25).reshape(5,5)
print(arr[2:5,1:5])

[[12. 13. 14. 15.]
 [17. 18. 19. 20.]
 [22. 23. 24. 25.]]


In [15]:
arr=np.linspace(1,25,num=25).reshape(5,5)
print(arr[3,4])

20.0


In [16]:
arr=np.linspace(1,25,num=25).reshape(5,5)
print(arr[0:3,1].reshape(3,1))

[[ 2.]
 [ 7.]
 [12.]]


In [17]:
arr=np.linspace(1,25,num=25).reshape(5,5)
print(arr[4,0:5])

[21. 22. 23. 24. 25.]


In [18]:
arr=np.linspace(1,25,num=25).reshape(5,5)
print(arr[3:5,0:5])

[[16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


# Great Job!