# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [ ]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
print(np.full(10,5))

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [ ]:
i = 0
a = []
for i in range(0,41):
  a.append(i+10)
  i+=1
print(np.array(a))


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [ ]:
i = 0
a = []
for i in range(0,21):
  a.append(2*i+10)
  i+=1
print(np.array(a))


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
i =0
a = []
for i in range(0,9):
  a.append(i)
  i+=1
b = np.array(a)
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(1)

array([0.5673314])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
a = np.random.rand(25)
b = a*2
print(b)

[0.34233444 0.75118757 0.81286153 0.62678383 0.73057921 1.29583269
 0.82152689 1.37550688 1.83058172 1.33288447 0.79778632 0.90701594
 1.41096636 0.58264982 0.26147294 1.24720021 0.58226957 1.51217989
 1.54522173 1.59281837 1.75448625 1.02793832 0.23459935 0.96576698
 0.79782488]


#### Create the following matrix:

In [ ]:
i = 0
a = []
for i in range(0,100):
  a.append((i+1)/100)
  i+=1
b = np.array(a)
b = b.reshape(10,10)
print(b)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
a = []
i = 0
for i in range(0,20):
  a.append(1/(1+i))
  i = i+1
a.reverse()
b = np.array(a)
print(b)

[0.05       0.05263158 0.05555556 0.05882353 0.0625     0.06666667
 0.07142857 0.07692308 0.08333333 0.09090909 0.1        0.11111111
 0.125      0.14285714 0.16666667 0.2        0.25       0.33333333
 0.5        1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
i = 0
a = []
for i in range(0,25):
  a.append(i+1)
  i+=1
b = np.array(a)
b = b.reshape(5,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
i = 0
a = []
for i in range(0,14):
  if((i+11)%5!=0):
    a.append(i+12)
    i+=1
b = np.array(a)
b = b.reshape(3,4)
print(b)

[[23 24 25]]


In [73]:
print(b[1,3])

20


In [77]:
a = b[:,0] - 10
a = a.reshape(3,1)
print(a)


[[ 2]
 [ 7]
 [12]]


In [80]:
i = 0
a = []
for i in range(0,25):
  a.append(i+1)
  i+=1
b = np.array(a)
b = b.reshape(5,5)
print(b[4,:])

[21 22 23 24 25]


In [81]:
i = 0
a = []
for i in range(0,25):
  a.append(i+1)
  i+=1
b = np.array(a)
b = b.reshape(5,5)
print(b[3:,:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!